FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

COPY . .

RUN dotnet restore
RUN dotnet build -c Release -o /app/build
RUN dotnet publish -c Release -o /app/publish

WORKDIR /app/publish
EXPOSE 5000

ENTRYPOINT ["dotnet", "emsAPI.dll"]